<?php

namespace FlordiaCampus\InfoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlumnosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnosRepository extends EntityRepository
{
}
